interface SyntheticDemoControlProps {
  incidentId: string | null; loading: boolean;
  onCreateIncident(): void; onRefresh(): void; onBootstrap(): void; onStartAgent(): void; onAdvanceAgent(): void; onPublishActive(): void; onCreateSafetyReview(): void;
  canBootstrap: boolean; canStartAgent: boolean; canAdvanceAgent: boolean; canPublishActive: boolean; canCreateSafetyReview: boolean;
}
export function SyntheticDemoControl(props: SyntheticDemoControlProps) {
  const action = (label: string, enabled: boolean, onClick: () => void) => <button type="button" disabled={props.loading || !enabled} onClick={onClick} className="rounded border border-fuchsia-500/40 px-3 py-2 font-mono text-[11px] uppercase disabled:opacity-50">{label}</button>;
  return <section aria-labelledby="demo-control-heading" className="rounded border border-fuchsia-500/40 bg-fuchsia-950/20 px-4 py-4"><p className="font-mono text-[11px] uppercase tracking-[0.25em] text-fuchsia-300">DEMO CONTROL</p><h2 id="demo-control-heading" className="mt-1 text-sm font-semibold text-slate-100">Guided Phase 6 actions</h2><p className="mt-1 text-sm text-slate-400">Every action reads persisted state. No autoplay, run-all, replay, reset, or automatic agent progression.</p><div className="mt-4 flex flex-wrap gap-2">{action("Create canonical incident", !props.incidentId, props.onCreateIncident)}{action("Bootstrap PRE_DISCHARGE", props.canBootstrap, props.onBootstrap)}{action("Start AgentRun", props.canStartAgent, props.onStartAgent)}{action("Advance Agent", props.canAdvanceAgent, props.onAdvanceAgent)}{action("Publish DISCHARGE_ACTIVE", props.canPublishActive, props.onPublishActive)}{action("Persist canonical SYN-CNT-010 contradiction", props.canCreateSafetyReview, props.onCreateSafetyReview)}{action("Refresh", Boolean(props.incidentId), props.onRefresh)}</div></section>;
}
